server:
  port: ${PORT:8081}

spring:
  application:
    name: pilot-service
  datasource:
    password: password
    url: jdbc:postgresql://${DATASOURCE_URL:192.168.99.100}:5432/pilotpaydb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}





