server:
  port: ${PORT:8081}

spring:
  datasource:
    password: password
    url: jdbc:postgresql://pilotpaydb:5432/pilotpaydb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true





